POST https://teste-node-g266.onrender.com/videos
Content-Type: application/json

{
  "title": "Video node",
  "description": "Esse é o primeiro video",
  "duration": 180
}

###

GET https://teste-node-g266.onrender.com/videos

###

PUT https://teste-node-g266.onrender.com/videos/777c0431-bd4b-43db-99e1-79950b889d8e
Content-Type: application/json

{
  "title": "Video 02",
  "description": "Esse é o primeiro video",
  "duration": 180
}

###

DELETE https://teste-node-g266.onrender.com/videos/777c0431-bd4b-43db-99e1-79950b889d8e